language: java
before_install:
 - curl -sSL https://get.rvm.io | bash -s stable --ruby
 # - wget http://dl.google.com/android/android-sdk_r18-linux.tgz
 # - tar -zxf android-sdk_r18-linux.tgz
 # - export ANDROID_HOME=`pwd`/android-sdk-linux
 # - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
