language: android

android:
  components:
    - build-tools-21.1.2
    - android-20
    - android-21
    - extra-google-m2repository
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-21

notifications:
  email: true

env:
  matrix:
    - ANDROID_TARGET=android-21  ANDROID_ABI=armeabi-v7a

before_install:
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd test -no-skin -no-audio -no-window &
  - gem install calabash-android

before_script:
  - ./scripts/wait_for_emulator.sh
  - adb shell input keyevent 82 &

script: calabash-android run app-debug.apk
